### PR TITLE
Renames Fake(Float,Math) to Alternative(Float,Math)

### PR DESCRIPTION
**Pull request by xfxf**
I mean, we've got Alternative Facts now, Alternative Floats & Math makes this legit...

### CODE REVIEW

**Comment by adtac** [comment]
Haha, nice one :D

Care to change the file names as well? `destruction.FakeFloat.AlternativeFloat` isn't quite as charming :P

**Comment by xfxf** [comment]
Ah, whoops, missed that!  Done, tested locally, appears to work.  I didn't think you'd actually accept this, I just couldn't resist running a regex over it and submitting a PR ;)

**Comment by sils** [comment]
love it :+1: from me, @adtac you gotta merge that ;)

**Comment by adtac** [comment]
Merged :)

**Pull request merged**
